### ISSUE TITLE
Dependency on com.springsource.org.apache.commons.lang

### ISSUE THREAD

**Issue by verglor** [nerdErg/grails-shiro#13]
Is there any special reason to use dependency on `org.apache.commons:com.springsource.org.apache.commons.lang` instead of regular `commons-lang:commons-lang` ? Both contain the same classes causing duplicates in classpath.

**Comment by pmcneil** [comment]
Probably not, apart from it previously being used. I'll see if we can remove/revert.

**Comment by pmcneil** [comment]
it seems we only use it for the NotImplementedException, so a minor dependency.
I have tested replacing with `org.apache.commons:commons-lang3:3.10` which required java 8 plus (and different package name) which breaks things a bit.

So - you can just exclude it and include the legacy `commons-lang:commons-lang:2.6` and that will work (tested). 

At this point I will not change the plugin until the next release (after we drop support for the grails 3 branch?), in which case I may just implement a native NotImplemented exception, because the change in package name for apache.commons.lang3 means anyone depending on catching the exception would have to change their code anyway... and I suspect nobody is catching it...

**Comment by verglor** [comment]
Hi @pmcneil, replacing it with `commons-lang3` would break things indeed. But using `commons-lang:commons-lang:2.6` dependency instead should be pretty safe one-line fix. Current springsource hacky dependency is also legacy.

**Comment by pmcneil** [comment]
I've just removed it completely - but it probably won't be released for a little bit.
